version: "1.0"

project:
  name: django-app
  description: A sample Django project deployed on Lyrid
  language: python
  framework: django
  
services:
  web:
    container_name: web
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn keywords_generator.wsgi:application --bind 0.0.0.0:8000 --timeout 30 --workers 2 # --reload  
    ports:
      - 8000:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
      - ./app/:/usr/src/app/
    expose:
      - 8000

volumes:
  static_volume:
  media_volume:

deploy:
  provider: lyrid
  region: apsoutheast1
  scaling:
    min_instances: 1
    max_instances: 3
