name: Keyword Generator
description: Generate keywords that are common from a PDF file
ignoreFiles: .env .venv __pycache__ mediafiles staticfiles
modules:
  - name: keyword-generator-module
    language: docker
    description: 
      ports:
      - alias: "http"
        port: 8080
    config:
      instance: "WjyaD7R4Zk"
    functions:
      - name: entry
        entry: wsgi.py
        description: The entry point for the function
