name: Keyword Generator
description: Generate keywords that are common from a PDF file
ignoreFiles: .env .venv __pycache__ mediafiles staticfiles
modules:
  - name: keyword-generator-module
    language: docker
    description: Module for django project
    functions:
      - name: entry
        entry: wsgi.py
        description: The entry point for the function
